#pragma once
#define STREAM_ENDIANNESS 0
#define PLATFORM_ENDIANNESS 0

#define WORLD_WIDTH   1000
#define WORLD_HEIGHT  1000

#define WORLD_HALF_WIDTH (WORLD_WIDTH / 2)
#define WORLD_HALF_HEIGHT (WORLD_HEIGHT / 2)
#define PRECISION_POS 0.05f

#define REQUIRED_BITNUM_POS 15